### ISSUE TITLE
Can you show me the code

### ISSUE THREAD

**Issue by pasBone** [bebaoboy/project-calendar#1]
Hey, buddy, where is the code in your video? I think the effect is very good. Can you show me

**Comment by bebaoboy** [comment]
Hello, this is a request from a client so I can't, unfortunately, share the code publicly. 
However, I can give you some headstart.

**Comment by pasBone** [comment]
> Hello, this is a request from a client so I can't, unfortunately, share the code publicly. However, I can give you some headstart.

Thank you. I just wanted to do a similar animation by sliding up and down to change the height of the container, but I didn't know how

**Comment by bebaoboy** [comment]
You can try using a Gesture Detector. The function `onHorizontalDragUpdate` will calculate the variable height of the container you want to slide up and down. 
Then just pass the height into your desired container.

**Comment by pasBone** [comment]
> You can try using a Gesture Detector. The function `onHorizontalDragUpdate` will calculate the variable height of the container you want to slide up and down. Then just pass the height into your desired container.

Thank you, Brother, I succeeded
